default: &default
        adapter: postgresql
        encoding: unicode
        username: postgres
        password:
        host: db

development:
        <<: *default
        database: foodancy_development

test:
        <<: *default
        database: foodancy_test
